### ISSUE TITLE
Remove from watch later seems to be missing

### ISSUE THREAD

**Issue by ghost** [Bluscream/mytube#8] opened 2020-02-27 17:49 UTC
**Environment Information (complete and add to the following information):**

- **OS:** `Windows 10 18363.657`
- **myTube!:** `3.9.24.0`
- **Beta:** `yes`

**Description:**
In the Watch Later section clicking on a video opens up a context menu. In this menu there used to be an option to remove the selected video from the Watch Later section. The option is available in context menus on videos in playlists in the Playlist section.

**Steps to reproduce:**

- Go to the Watch Later section (Später ansehen in German)
- Right-click on a video
- See, that option to remove video from Watch Later is gone

**Expected behavior:**
The context menu is expected to show an option to remove the video from Watch Later.

**Screenshots:**
This is how the menu looks in Playlists
<img width="222" alt="menu in playlist" src="https://user-images.githubusercontent.com/17417041/75470996-d6608080-5991-11ea-87f4-07812693426c.png">

This is how the menu looks in Watch Later
<img width="194" alt="menu in watch later" src="https://user-images.githubusercontent.com/17417041/75471011-dd878e80-5991-11ea-8e04-0fa4d851c0b0.png">

**Comment by maximushugus** [comment] 2020-03-29 10:17
I can confirm that the problem is still here today, even in french.

**Comment by Ryken100** [comment] 2020-06-01 21:00
This should be fixed now

**Closed as completed by Ryken100** 2020-06-01 21:00 UTC
Labels: bug
